### ISSUE TITLE
Error while run the server

### ISSUE THREAD

**Issue by d-biswas** [multunus/onemdm-server#10]
Hi, I've installed the onemdm-server in my local machine and found the following error when head over to http://localhost:3000/admin

```
Started GET "/admin/login" for 127.0.0.1 at 2017-07-18 13:09:51 +0600
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
  ActiveRecord::SchemaMigration Load (1.0ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by ActiveAdmin::Devise::SessionsController#new as HTML
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-24baa21a24c8/app/views/active_admin/devise/shared/_links.erb (6.5ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-24baa21a24c8/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out (187.1ms)
Completed 500 Internal Server Error in 1301ms (ActiveRecord: 5.0ms)

ActionView::Template::Error (TypeError: Object doesn't support this property or method):
     6:   <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>
     7:
     8:   <% ActiveAdmin.application.stylesheets.each do |style, options| %>
     9:     <%= stylesheet_link_tag style, options %>
    10:   <% end %>
    11:   <% ActiveAdmin.application.javascripts.each do |path| %>
    12:     <%= javascript_include_tag path %>
  execjs (2.7.0) lib/execjs/external_runtime.rb:39:in `exec'
  execjs (2.7.0) lib/execjs/external_runtime.rb:21:in `eval'
  execjs (2.7.0) lib/execjs/external_runtime.rb:46:in `call'
  coffee-script (2.4.1) lib/coffee_script.rb:78:in `compile'
  sprockets (3.7.1) lib/sprockets/coffee_script_processor.rb:21:in `block in call'
  sprockets (3.7.1) lib/sprockets/cache.rb:85:in `fetch'
  sprockets (3.7.1) lib/sprockets/coffee_script_processor.rb:20:in `call'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `yield'
  sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.7.1) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.7.1) lib/sprockets/utils.rb:200:in `dfs'
  sprockets (3.7.1) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
  sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
  sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `yield'
  sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.7.1) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.7.1) lib/sprockets/base.rb:73:in `find_all_linked_assets'
  sprockets (3.7.1) lib/sprockets/manifest.rb:134:in `block in find'
  sprockets (3.7.1) lib/sprockets/manifest.rb:133:in `each'
  sprockets (3.7.1) lib/sprockets/manifest.rb:133:in `find'
  sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `each'
  sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `map'
  sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `precompiled_assets'
  sprockets-rails (3.2.0) lib/sprockets/railtie.rb:35:in `asset_precompiled?'
  sprockets-rails (3.2.0) lib/sprockets/railtie.rb:251:in `block (3 levels) in <class:Railtie>'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:359:in `call'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:359:in `precompiled?'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:363:in `raise_unless_precompiled_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:348:in `find_debug_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:229:in `block in lookup_debug_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `each'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `detect'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:228:in `lookup_debug_asset'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:170:in `block in stylesheet_link_tag'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in `map'
  sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in `stylesheet_link_tag'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-24baa21a24c8/app/views/layouts/active_admin_logged_out.html.erb:9:in `block in _____uby___x___lib_ruby_gems_______bundler_gems_activeadmin___baa__a__c__app_views_layouts_active_admin_logged_out_html_erb___166388050_78462600'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-24baa21a24c8/app/views/layouts/active_admin_logged_out.html.erb:8:in `each'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-24baa21a24c8/app/views/layouts/active_admin_logged_out.html.erb:8:in `_____uby___x___lib_ruby_gems_______bundler_gems_activeadmin___baa__a__c__app_views_layouts_active_admin_logged_out_html_erb___166388050_78462600'
  actionview (4.2.4) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.4) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.4) lib/action_view/template.rb:143:in `render'
  actionview (4.2.4) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.4) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.4) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.4) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.4) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.4) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.4) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.4) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.4) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.4) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.4) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.4) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  C:/Ruby22-x64/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:43:in `render'
  responders (2.4.0) lib/action_controller/responder.rb:238:in `default_render'
  responders (2.4.0) lib/action_controller/responder.rb:170:in `to_html'
  responders (2.4.0) lib/action_controller/responder.rb:163:in `respond'
  responders (2.4.0) lib/action_controller/responder.rb:156:in `call'
  responders (2.4.0) lib/action_controller/respond_with.rb:211:in `respond_with'
  devise (4.3.0) app/controllers/devise/sessions_controller.rb:12:in `new'
  actionpack (4.2.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/head.rb:13:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rollbar (2.14.1) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
  rollbar (2.14.1) lib/rollbar.rb:145:in `scoped'
  rollbar (2.14.1) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rollbar (2.14.1) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  newrelic_rpm (4.2.0.334) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  rack (1.6.8) lib/rack/content_length.rb:15:in `call'
  rack (1.6.8) lib/rack/handler/webrick.rb:88:in `service'
  C:/Ruby22-x64/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  C:/Ruby22-x64/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  C:/Ruby22-x64/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (5.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (2.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (1642.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.5ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (1.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (1.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (1288.1ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (2993.5ms)
```
Would you please help me on this? Thanks in advance. Please note that I'm using a Windows 10 machine

**Comment by leenasn** [comment]
@d-biswas can you run it on an Ubuntu or Mac machine and let me know? 

Can you also try with Ruby version 2.3?
